# Application name
spring.application.name=server

# Server port
server.port=8080

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/ticketdb?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2
spring.datasource.username=ykg8gP5mmQkdozJ.root
spring.datasource.password=B7WjkarwyTZA4UG2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
